logging:
  level:
    dev.rpilab.hello: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: false
  otlp:
    metrics:
      export:
        enabled: false

spring:
  web:
    resources:
      cache:
        cache-control:
          max-age: 0
          cache-public: false
