spring:
  application:
    name: hello-rpilab
  cache:
    type: redis
  web:
    resources:
      cache:
        cache-control:
          cache-public: true
          max-age: 365d
      chain:
        strategy:
          content:
            enabled: true

management:
  observations:
    key-values: &tags
      application: ${spring.application.name}
      service: ${spring.application.name}
      source: ${spring.application.name}-${random.uuid}
  metrics:
    tags: *tags
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    sampling:
      probability: 0.1
  otlp:
    metrics:
      export:
        step: 30s
        url: http://localhost:4318/v1/metrics
    tracing:
      endpoint: http://localhost:4318/v1/traces
  endpoint:
    health:
      probes:
        enabled: true
        add-additional-paths: true
      show-details: always
      group:
        readiness:
          include:
          - readinessState
          - redis
  endpoints:
    web:
      exposure:
        include: health, metrics
  server:
    port: 8081

server:
  port: ${PORT:8080}

logging:
  level:
    io:
      micrometer:
        registry:
          otlp: off
      opentelemetry:
        exporter:
          internal:
            http: off

app:
  info:
    server:
      hostname: rpilab.local
  ninjas:
    api:
      url: https://api.api-ninjas.com
  weather:
    api:
      url: https://api.weatherapi.com
  location: Paris
