#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: hello-rpilab-config
type: Opaque
stringData:
  provider: sample
  type: config
  app.info.server.hostname: #@ data.values.server_hostname if "server_hostname" in data.values else "hello-rpilab"
  app.ninja.api.key: #@ data.values.ninja_api_key
  app.weather.api.key: #@ data.values.weather_api_key
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: hello-rpilab-config
spec:
  ref:
    apiVersion: v1
    kind: Secret
    name: hello-rpilab-config
